### ISSUE TITLE
Asynchronous asserts need to fire immediately, not to wait for WaitForAsserts

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#103]
Currently, in the following code snippet:

```
	tc.AssertInfo(t, "expected reboot to happen", CheckRebootInfo)
	tc.WaitForAsserts(t, *timewait)
```

The first call simply registers the assert with TestContext, but otherwise doesn't do anything. It takes a 2nd call for the assert function to actually start firing.

This is NOT what the original proposal meant. In the original proposal WaitForAsserts was meant to be a simple barrier for asserts that start running immediately after AssertInfo call is made.

**Comment by mydatascience** [comment]
Done
