### ISSUE TITLE
Usage of asynchronous asserts is still overly complicated

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#104]
If for a simple test reboot counter we have to write this much extra code https://github.com/lf-edge/eden/blob/master/tests/reboot/check_reboot.go clearly things can be simplified.

I'd like to suggest we take a long step back and start from the very basics. Mainly, lets just start with implementing TestContext.AddProcInfo, TestContext.AddProcLog and TestContext.AddProcMetric -- all of these functions will take an argument of a Processor function that simply accepts individual entries of Info, Log and Metric type, does whatever it needs to do with them and if it returns `err != nil` gets deregistered (for as long as it returns nil it keeps getting called).

That way we can have, effectively, an open-ended stream processing of the 3 streams and we can figure out what else we can build out of that step-by-step.

**Comment by mydatascience** [comment]
We have this https://wiki.lfedge.org/display/EVE/Objects+and+methods+for+SDK and now refactoring the code, hiding typical AssertFunctions in the SDK. 
Generally agree to make it much more simple
