### ISSUE TITLE
Remove individual makefiles in separate tests

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#106]
I would like to build the test binary by calling 
eden test build <path of the folder> 

This calls make utility and places the binary in the same folder.  

Then run the test by calling 
eden test run <path of the folder> 

Please confirm @rvs

**Comment by sadov** [comment]
I do not agree with this idea. Firstly, from the very beginning, we considered EDEN as a separate application, which is only required to run the EVE testing runtime environment and binary test files. Without the need to install and configure any external development environment. If we talk about the need to make, go, etc. to run the tests, we completely change this concept.

Moreover, hiding the “make” machinery under the hood of some mysterious tool is not what the programmer usually expects.

And, of course, this makes it very difficult to move the tests to another place. For example, some time ago, the issue of transferring EVE integration tests directly to the EVE development tree was discussed. In this implementation, you can simply get any of our test directories, move it to any place, change something, rebuild the test binary file and send it to testers who simply use it with the `eden test` command.

**Comment by mydatascience** [comment]
I do not restrict having make for a sophisticated developer if he wants to. But I'd require some simplistic behavior and requirements like in Layer 2 https://wiki.lfedge.org/display/EVE/Tests for the sake of usability and maintainability of the community.

**Comment by sadov** [comment]
Are there really any problems with "make" in the community?

**Comment by rvs** [comment]
I think you're both right @sadov @mydatascience 

Here's how I look at this: ultimately, it is very likely that the tests will be driven by the Makefile but it won't be Eden's Makefile -- it will EVE's Makefile.

When it comes to Eden -- I don't actually mind the Makefile infra, but it feels odd to use it there compared to having a top level Eden command.

At the same time -- this is one of those issue where I feel we're in a transition state and it maybe best to figure out where that transition leads us first. IOW, if we happen to move all the tests to EVE in the next few weeks -- that'll provide a very clear answer for top level eden test command vs. Makefile target.

**Comment by mydatascience** [comment]
Not to do. Did escripts
