### ISSUE TITLE
States SDK

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#108]
We would like to have some States that are formed by several messages or some changes that happen since the monitoring time. 
State is a defined structure that holds current state of the system (adam+eve(s)).
State is filled once we start monitoring and then we need to support the eventually consistent condition of the object by processing messages from Log/Info/Metrics.
Many routines may read the state ((async), only one async routine updates the State. 
 A developer can call getState and get a State object. For example I may wanna call tc.getState.lastreboot and see at any time when was last reboot done. 

Described also in https://wiki.lfedge.org/display/EVE/Objects+and+methods+for+SDK

So I may write something like: 
```
tc.Monitorstate()
firstreboottime = tc.getState().fornode("node1").lastreboottime

tc.getNodeByName("node1").reboot()

while (not timeout)
{
  if(firstreboottime!=tc.getState().fornode("node1").lastreboottime)
    {
     t.log("Rebooted")
     return true
    }
  sleep(10)
}
t.log("Reboot timeout")
return false
```

**Comment by rvs** [comment]
+1 for the definitions here, but is there a PR for this? I thought there was but I can't seem to find it @mydatascience
