### ISSUE TITLE
Get rid of editing EVE's Makefile on the fly

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#11]
Currently, fixIPs.sh script edits EVE's Makefile on the fly. This is not particularly flexible and I have introduced the following variables in EVE Makefile to make it go away:
  * QEMU_OPTS_NET1
  * QEMU_OPTS_NET1_FIRST_IP
  * QEMU_OPTS_NET2
  * QEMU_OPTS_NET2_FIRST_IP

Please migrate to them

**Comment by sadov** [comment]
Done at PR14.

**Comment by rvs** [comment]
Closed with #14
