### ISSUE TITLE
Need to allow pod deploy to be able to accept a local file

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#122]
While it is pretty cool that `./eden pod deploy ... https://foo.bar/baz` will helpfully download a given image for me into the locally configured cache, it should be possible to specify a file that is already in the cache. I suggest we introduce a `file:///XXXX` URL to handle this so that I can do:

```
./eden pod deploy ... file:///XXXXX
```

and the effect will be serving that file up from the local eserver

Once we do that we may actually want to simply pass http(s) URLs onto EVE (without involving a local eserver) so that EVE itself downloads them (and yes this will mean an extra data store).

**Comment by giggsoff** [comment]
About sending url to EVE (for remote image): Eden need to know sha256 and size of image. I can add them as flags to pod deploy command.

**Comment by rvs** [comment]
Ah! You're right of course @giggsoff . Well, lets just introduce support for local files then (I think file:// URI would be fine -- but I'm open to other ideas too)

**Comment by mydatascience** [comment]
Done
