### ISSUE TITLE
eve ssh needs to add config item if it is missing

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#123]
Doing `./eden eve ssh` I expect Eden to add ssh key to the EVE's config (if it is missing) but it simply fails:

```
INFO[0000] Try to SHH 192.168.0.165:22 with key /Users/roman/src/lfe/eden/dist/certs/id_rsa
ssh: connect to host 192.168.0.165 port 22: Connection refused
FATA[0000] ssh error: exit status 255
```

Note that if I first add the key manually via

```
./eden controller -m adam:// edge-node update ...
```

then ssh command works as expected

**Comment by giggsoff** [comment]
Hi @rvs now Eden adds ssh key on step of onboard (after successful onboard).
You can see it by issue:
`./eden controller edge-node get-config -m adam://`
Your error is about connection problems..

**Comment by rvs** [comment]
Actually, I did do `edge-node get-config -m adam://` and config showed no key added

**Comment by giggsoff** [comment]
Intresting. 
The way Eden doing things: Eden wait for onboard success (no device before -> new device) and add key and device model.
So, If Adam already has device, or `eden eve onboard` was not successful, magic will not come.
I will recheck it, thank you.

**Comment by rvs** [comment]
Hey @giggsoff -- so I played with it some more today -- and here's what I've found:
   1. you're right -- after a clean start of Eden (from scratch) the ssh key IS present in the config -- that's good
   2. because of EVE's internal convergence issues -- it may actually take quite a bit of time for EVE to actually allow ssh in

Because of #2 it looks like #1 wasn't working. So at least this mystery is solved.

Now, as we've agreed, could you please also improve eve ssh command to make it check for the ssh key in config and add it there if it is missing (I understand that we may also have some way to make tests more safe -- but I think this is needed regardless -- and it should be pretty easy to implement).

**Comment by mydatascience** [comment]
Done
