### ISSUE TITLE
Actual status of EVE if it's unavalable in eden status

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#126]
Once onboarded, remote EVE doesn't change the status even if it has gone offline.
We need to find some discovery mechanism to get the actual  remote EVE status and display it in `eden status`

**Comment by rvs** [comment]
Hey @mydatascience -- can you guys prioritize this a bit? This is especially relevant given recent confusion about the need for `eden eve onboard` command. So my suggestion would be to include that help text into eden status output:

```
eden status
...
EVE is running ... (but it isn't onboarded -- make sure to run  eden eve onboard to complete the onboarding sequence)
```
