### ISSUE TITLE
Add some tool for working with media (like SD card) 

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#147]
As a user I want to get all info about what is contained on some media. (/dev/diskX)  Useful for RPI. 
1) Eve version
2)Last update time
3) Some data about the config or the config itself

**Comment by rvs** [comment]
Big +1 to this! One word of caution tho -- I'd stay away from actually writing bits to the media -- reading is totally fine tho.

**Comment by mydatascience** [comment]
Done
