### ISSUE TITLE
Stabilize running VMs in different configurations

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#148]
Currently there is a problem of running VMs for RPi4. We need to find something that works or find out why are VMs not working and fix if possible

**Comment by rvs** [comment]
Can you be specific as to what the problem actually is @mydatascience ?

**Comment by mydatascience** [comment]
The problem is that VMs look to be "started" but they are not accessible.

**Comment by rvs** [comment]
Is it happening under Xen, KVM or both? Also, any clues from the VM console you may be able to provide?

**Comment by rvs** [comment]
It appears we're past the initial hurdles here @giggsoff @mydatascience -- can this be closed?

**Comment by mydatascience** [comment]
Works
