### ISSUE TITLE
Support custom EVE repo and custom EVE image

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#204]
Make it easy to use custom build image from the start and make one command to build EVE for Eden from  the custom repo

**Comment by deitch** [comment]
That would be nice, although I think a perfectly fine interim step would be

1. Go to eve repo and build it
1. Run eden pointing it at a separate eve image

It needs to be clear as to how the config gets loaded in. E.g. normally eve builds config right into the `live.img`, which sort of can be overridden (see [this eve PR](https://github.com/lf-edge/eve/pull/1285)).

It also should be simple, so, e.g. if I have running components, I can do `eden eve start --eve-img=/some/path.img` or similar.

**Comment by rvs** [comment]
Btw with the documentation that @deitch provided recently -- should we close this issue? @eriknordmark does the current workflow with make eve work well for you?

**Comment by mydatascience** [comment]
Done
