### ISSUE TITLE
Documentation is sorely lacking

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#206]
I was discussing earlier with @giggsoff . The work done here in the last few months is great. It makes it so much easier to launch one or more eve devices, launch adam, etc. etc.

It also has a ton of capabilities, but it is almost undocumented. I have no idea, short of reading the code, how to do multiple things I need to do as part of normal development. Here are some examples:

* run when I don't have nested virtualization, e.g. running on a cloud-provider node. It still works, but I had to hunt down to run `eden start --eve-accel=false`. The starting point should not be, "here's how to disable acceleration", but rather, "when running in a VM without nested virtualization, e.g. on AWS, you need to disable hardware acceleration, here is how."
* change the config for a device on adam
* export the config json for a device on adam
* point to a different eve image, whether docker-based or local filesystem
* change the `/var/config`, e.g. a different controller

There is a lot more, but eden truly has the potential to be **the** entrypoint to eve for someone coming at this from zero existing experience, and **the** way even those with experience run any combination. I think it has the majority of the capabilities it needs, but It desperately needs the documentation to make that happen.

**Comment by deitch** [comment]
Also, it really needs an architecture/process document. "Here is what eden manages and how it works". That would make it easier for people to understand, easier to onboard new contributors, but also (and perhaps especially) make it easy for people with good ideas that we haven't thought of to come up with great usage ideas.

**Comment by rvs** [comment]
I can't +1 this enough @deitch -- I've been trying to nudge the team in that direction (hi there @giggsoff @mydatascience  ;-)) but being an insider myself -- a lot of times I too tend to think that thing are obvious.

I really can't think you enough for starting your documentation efforts, but I also feel that perhaps you @eriknordmark and everyone working on EVE should just block a bit of time to give Eden a try and share their experience.

So... perhaps an Eden hackthon sometime? What do you think?

**Comment by deitch** [comment]
> an Eden hackthon sometime? What do you think?

That is a good idea. Scheduling might be a bit challenging - France, CA, India, Eastern Europe, Israel - but we can do it.

Here is a thought. Let's have someone record a basic introduction to eden: here is what it does, here is me doing some basic tasks, look what happens. We send that out to participants a week or so before, then everyone comes to the hackathon with a list of things they would like to be able to do. Some may already be there but need documentation, others might not be, etc. It will make it more productive in a shorter timeframe, which we need given the timezone constraints.

Thoughts?

**Comment by mydatascience** [comment]
I'll close this for now. Feel free to reopen with some details
