### ISSUE TITLE
The command-line structure is a little confusing

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#211]
Consider the following:

* `eden controller` does some things, but `eden adam` does others, even though `adam` _is_ the controller
* `eden controller edge-node` lets me do some edge node things, like update or remove a baseos image, reboot, and get the current config, but `eden pod` lets me do pod things on an edge node
* `eden controller edge-node get-config` lets me get the actual config json for a node, but `eden controller edge-node update` lets me set config properties
* `eden reconf` lets me get the actual config json for a node, but so does `eden controller edge-node get-config`, while `eden reconf` also lets me set the config

This needs a clean restructuring to make it easier to understand and use. I can propose some options below.

Copying some thoughts from a previous issue:

At this point Eden has grown quite a bit into, effectively, a system that manages various runtime and static objects to make different scenarios of working with EVE possible. These objects are:

Static objects:

* Eden's own configs/contexts (current config subcommand)
* EVE's controllers (current controller subcommand)
* x509 certificates (current certs subcommand)
* Edge Containers (current ociimage subcommand)
* EVE live images (current eve-update subcommand)
* Test suites/Test scripts (current test subcommand)

Dynamic objects:

* Adam instances (current adam subcommand)
* Redis instances (current redis subcommand)
* Eserver instances (current eserver subcommand)
* EVE instances (current eve subcommand)

On top of that we have what I would describe as top-level actions (those act on a collection of objects described in a current context):

* setup (makes sure that all of the local objects defined in my current context are up-to-date)
* clean (it actually isn't clear to me anymore what it does -- but logically it should probably an opposite of setup in a sense that it would clean any transient resources -- like disk space or docker cache that setup may have created)
* start (makes sure that all the dynamic objects get started)
* status (gives me a view of the objects currently known to Eden)
* stop (makes sure that all the dynamic objects get stopped)

**Comment by deitch** [comment]
First, I think the high-level eden-focused commands make sense:

```
  clean       clean harness
  config      work with config
  help        Help about any command
  setup       setup harness
  start       start harness
  status      status of harness
  stop        stop harness
  test        Run tests
  utils       Eden utilities
```

We also should have the high-level commands to control services:

```
eve # including console, ssh, status, start, stop
adam
redis
eserver
```

Beyond those, everything to interact with and control running eve instances should be under one root point. I think `eden device` makes sense, `eden controller` is fine too, but everything should be there, similar to:

```
eden device get-config
eden device set-config
eden device info
eden device logs
eden device metrics
eden device reboot
eden device update
eden device image-update
```

**Comment by rvs** [comment]
I general, I very much agree that some streamlining of the top-level CLI command structure is very much needed (believe it or not -- we've done one round of cleanups already).

What you suggesting makes sense, but I would also like to let is stew for a couple of weeks to see what other functionality will emerge in Eden. Then we can have one holistic look and change the structure.

Makes sense?

**Comment by deitch** [comment]
> believe it or not -- we've done one round of cleanups already

I believe it. This stuff is emergent. If we tried to plan the perfect CLI and flags from day 0, we would never have built anything useful.

> What you suggesting makes sense, but I would also like to let is stew for a couple of weeks to see what other functionality will emerge in Eden. Then we can have one holistic look and change the structure

If you want to, sure. I have a leaning towards, let's just fix it, and add new emerging commands in that structure. But I don't have the time to clean it up now anyways.

**Comment by mydatascience** [comment]
Closing. We fixed this. Feel free to reopen
