### ISSUE TITLE
CI should be automated, not manual Jenkins

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#218]
CI currently is run manually on Jenkins. That means we cannot make it a blocking part of PRs - "do not allow merge until CI has passed" - or an automated part of post-merge.

We need to move it from Jenkins into a support CI-as-a-service. GitHub Actions probably is easiest, but circleci and drone and others are fine.

In any case, this is an OSS project and needs to have open CI.

**Comment by mydatascience** [comment]
It's not manual. It's triggered by Github push, but now it's itmo repo. I plan to integrate Jenkins to Github, so you know whether the PR pass the test.

**Comment by deitch** [comment]
Got it. OK, I will close this issue and open a new one to reflect.
