### ISSUE TITLE
eden clean no longer cleans fully

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#251]
I am not sure at what point in the last two weeks it changed, but `eden clean` no longer completely resets.

When I do `eden setup` followed by `eden start`, I have a nice initialized setup that I can use. I then do `eden stop` to stop it, and `eden clean` to clear out all artifacts from `setup`.

However, it appears that some of the files/config (perhaps disk?) linger, and a new `setup` followed by `start` seems to have lingering artifacts. @giggsoff explained to me by chat that `eden clean` had changed to some degree, and that I now needed to do `make clean` to completely clean it.

This isn't good. `make clean` is universally understood to clean everything up, including built binaries, etc. `eden clean`, on the other hand, should just be cleaning up the artifacts created by `eden config` or `eden setup`. If I run `eden clean`; I now need to recreate the `eden` binary.

@giggsoff recommended opening an issue, so here it is.

**Comment by mydatascience** [comment]
Please feel free to reopen. Eden clean behavior is described in the docs
