### ISSUE TITLE
Instructions on how to use GCP are not sufficient

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#256]
The instructions on how to use GCP are very sparse, leave a lot of questions that make it hard to get started.

Here is the entire set:

-----BEGIN-----
## Google Cloud support
Eden is enough to deploy Eve on Google Cloud. We are going to make it one command, but now the process is: 
* Make an image 
* Upload it to GCP and run 
* start eden (if not started yet) 
* Onboard eve (use `eden eve onboard`)

Step 1 : Make an image. You need to specify IP of Adam, by defalut Adam is a container inside machine with Eden, so put there an IP that is accessible from gcp
```
make CONFIG='--devmodel GCP' build
./eden config set default --key adam.eve-ip --value <IP of Adam/Eden>  
./eden setup
```
Step 2 : Upload image to gcp and run it. You will need a google service key json. https://cloud.google.com/iam/docs/creating-managing-service-account-keys 
```
./eden utils gcp image -k  <PATH TO SERVICE KEY FILE>  upload <PATH TO EVE IMAGE>
./eden utils gcp vm -k <PATH TO SERVICE KEY FILE> 
```
vm is named eden-gcp-test
`eden utils gcp` supports vm-name image-name and bucket-name  parameters

Step 3 : Start eden and onboard Eve
```
./eden start
./eden eve onboard
```
-----END-----

This leaves a lot of questions; you really cannot use it without the answers to them:

#### Adam IP?

The first step says: "Make an image. You need to specify IP of Adam, by defalut Adam is a container inside machine with Eden, so put there an IP that is accessible from gcp"

So do you need to run eden on a machine that is accessible from the public internet, or at least from Google Cloud? Does it need certain ports open? Which ones? Or does eden start adam _also_ on GCP?

#### Service Account Key

The second step says: "Upload image to gcp and run it. You will need a google service key json"

Generally, service account keys are keys tied to service accounts, which are independent entities. Do you need to make a service account and then a key? Why don't we authenticate using the actual user?

#### Adam-Eve-IP?

In the instructions, it says to set the config value `adam.eve-ip`. This is very confusing. Is it the IP where adam is running? Where eve is running? If it is the first, why is it called `adam.eve-ip` and not `adam-ip`, but there already is one with that name, so how is it different?

#### Image to upload?

One of the steps says:

```
./eden utils gcp image -k  <PATH TO SERVICE KEY FILE>  upload <PATH TO EVE IMAGE>
```

OK, the service key file is the one you saved from earlier. But where is the "PATH TO EVE IMAGE"? It isn't obvious, since it is generated by `eden setup`. We need to say where the image is, and, even better, make it part of the upload, since eden generated it in the first place.

#### The Design

In the end, I think the above come down to the design. What component runs where? How do eden, eve and adam talk to each other? What are the requirements? 

This is just a documentation issue, not a functionality one.

**Comment by deitch** [comment]
To add to this. Normally, when you want to run it locally, you go to the eve dir and run:

```
make eve
```

So that it gets the docker image. But here we are using `make build`. That can trip people up. Why is it different? Why does it need to be?

**Comment by deitch** [comment]
Oh wait. `make CONFIG='--devmodel GCP' build` is to be done for `eden`? You need a completely separately built eden for that? That is confusing.

**Comment by mydatascience** [comment]
We are not building Eve in Eden. 
The only difference is setup. 
Yes, make CONFIG='--devmodel GCP' build is just creating a different config with devmodel GCP
In fact you don't need that if you want to have a separate config. Just create a new profile and add gcp as a devmodel.

**Comment by deitch** [comment]
> We are not building Eve in Eden.
> The only difference is setup.

Then we shouldn't be doing `make build`, which actually builds the binary.

> In fact you don't need that if you want to have a separate config. Just create a new profile and add gcp as a devmodel.

That is great! It definitely is the way something like this should work. Can we change the instructions to explain how to do that, instead of the `make build`?

**Comment by mydatascience** [comment]
```
make clean
make build
./eden config add default
./eden config set default --key devmodel --value GCP
./eden config set default --key adam.eve-ip --value 35.227.137.74 
./eden setup
```

Will put this in the updated README

**Comment by rvs** [comment]
Yeah run into the same issue as well yesterday -- lets update READEM ASAP @mydatascience

**Comment by mydatascience** [comment]
#262

**Comment by mydatascience** [comment]
Closing until it still cause troubles
