### ISSUE TITLE
GCP uses same name for everyone running it, causes one to break the other

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#259]
When using gcp mode, it uploads a disk image named `eden-gcp-test` and creates a VM named `eden-gcp-test`. This has two serious shortcomings:

1. It makes it hard for me to find the one I created, but far more importantly:
1. It makes it likely for someone to break the other. If I run it and start, and 5 mins later you run it, you will overwrite and ruin mine. Oops.

**Comment by rvs** [comment]
+1000!

**Comment by mydatascience** [comment]
Fixed
