### ISSUE TITLE
Provide some kind of a progress bar for long running operations

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#26]
There's a few operations in eden that can be potentially long running like downloading from Docker HUB, etc. It would be great to provide some kind of a progress bar for those or at least indicate that the operation is still 'in progress'. Right now I' have:

```
eden eve download ...
```

sitting there 7 min in -- and I have no idea whether I should wait some more, interrupt it, etc. All I see is:

```
DEBU[0006] DownloadEveFormDocker run: /Users/roman/src/lfe/eden/dist/bin/eden-darwin-amd64 eve download --eve-tag=5.1.11 --eve-arch=amd64 -d /Users/roman/src/lfe/eden/dist/eve/dist/amd64 --baseos=false
```

**Comment by sadov** [comment]
Fixed on [PR43](https://github.com/lf-edge/eden/pull/43).
