### ISSUE TITLE
GCP mode requires firewall rule to allow outbound

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#260]
The GCP project has a firewall that blocks outbound traffic. This makes it impossible for the eve device run in GCP mode to onboard. You need to enable the firewall to allow traffic to your adam node.

This issue is for two distinct items. At some point, let's split them into 2 issues:

* This _must_ be documented. It is not enough to assume the user knows. The document must include:
   * that you need to enable the firewall rule
   * where to find the firewall rule to enable it (Home->Networking->VPCNetwork->Firewall->gcp-eden-out)
   * how to test that it is open correctly
* This should be automated

**Comment by mydatascience** [comment]
```
#!/bin/bash
extIP=$(gcloud compute instances describe eden-gcp-test  --format='get(networkInterfaces[0].accessConfigs[0].natIP)' --zone=us-west1-a)
gcloud compute firewall-rules create rulezz --allow all --source-ranges=$extIP
```

**Comment by deitch** [comment]
> This must be documented

I didn't mean here in the issue. It needs to be merged into the official docs.

**Comment by mydatascience** [comment]
yes. Sure

**Comment by mydatascience** [comment]
```
#!/bin/bash
BWD=$(./eden utils gcp vm get-ip -k ./../google.json)
echo "the IP is $BWD"
./eden utils gcp firewall -k ./../google.json  --source-range $BWD --name some_unique_name
```

**Comment by mydatascience** [comment]
Documented in Readme
