### ISSUE TITLE
seems like 'eden setup' starts up Adam

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#266]
It is confusing that when running `eden setup` it somehow starts Adam. I don't think there are any steps in setup action that require Adam to be running. If my hunch is correct -- can we please remove Adam start from `eden setup`?

**Comment by giggsoff** [comment]
We need to get root-certificate.pem from Adam and put it inside config partition of EVE. So, we need to start Adam and request certificate from it.

**Comment by rvs** [comment]
It would be really nice if we can figure out a way of how to do this without starting Adam. @deitch -- can you suggest something?

Short of @deitch coming up with a brilliant idea -- we need to at least shut Adam down at the end of eden setup step (but really -- lets figure out a way how we can NOT start Adam and still get the cert).

**Comment by deitch** [comment]
I had noticed that it started adam too, was wondering about it.

> We need to get root-certificate.pem from Adam and put it inside config partition of EVE. So, we need to start Adam and request certificate from it.

Where is the eden code that does it? Is it this `eden utils certs` command from [here](https://github.com/lf-edge/eden/blob/814ce472787e4962c77497b09f5f9d0748888cb8/pkg/eden/eden.go#L368-L378)?

**Comment by deitch** [comment]
It looks like [here](https://github.com/lf-edge/eden/blob/814ce472787e4962c77497b09f5f9d0748888cb8/pkg/eden/eden.go#L104-L106) it is just starting adam with `--auto-cert=true` to generate the certs. This just wraps the two steps of adam:

1. create the cert
1. start adam (and then for eden, retrieve the cert)

You can just run the adam command to generate certs, place them in the right place, tell adam to use those on start (volume mount into the container), and it should be fine.

**Comment by rvs** [comment]
Hey @giggsoff -- any thoughts on what @deitch mentioned -- I didn't see it in #269 that I just merged -- hence asking.

**Comment by giggsoff** [comment]
In future PR I will add Adam's stop, now, unfortunately, it is not ready.

A few words about the process: a few months ago Eden made root-certificate.pem himself. But now the transition to docker volumes is made without mounting to a directory and there is no way to drop the certificate into directory of Adam. Alternatively, we can make Adam's endpoint to import the certificate.

**Comment by rvs** [comment]
Make sense @giggsoff -- I guess it also comes down to who actually owns the generation of the cert. Having a model where it is Eden makes sense to me. The only issue with using a management API is that it makes bootstrapping cycle a bit non-trivial for Adam.

So... instead... what if we simply make Adam recognize a cert pair passed via environment variables? That way -- you can still have Eden in the driver seat but you don't have to rely on volumes or anything like that -- it is very straightforward option for Adam.

WDYT @deitch @giggsoff ?

**Comment by deitch** [comment]
@rvs 's comment makes sense. Adam accepts certs from the outside - that is its default operating mode - but can be made to create its own certs, either as a separate command or with `--auto-cert`, as we have done here.

I see a few simple options:

* have adam container mount a directory with a cert generated by eden (or by adam in CLI mode, i.e. not daemon) - why would this not work?
* create a docker volume and place the certificate there, then mount it to adam

These just are variants on what @rvs said.

**Comment by deitch** [comment]
I will comment on the PR

**Comment by mydatascience** [comment]
If everybody is fine with the current implementation I'd close it
