### ISSUE TITLE
info command doesn't explain how to use it

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#27]
When I run `eden info` it tells me to `Error: requires at least 2 arg(s), only received 0` and then prints:

```
Usage:
  eden info [flags]

Flags:
  -h, --help   help for info

Global Flags:
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")
```

It is not clear from this what 2 args it expects me to pass to it

**Comment by sadov** [comment]
Fixed on [PR43](https://github.com/lf-edge/eden/pull/43).
