### ISSUE TITLE
Get rid of  most make targets & put everything in the eden dir

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#271]
A compiled eden should be enough for EVE management. 
I suggest that all artifacts are stored in eden folder in config instead of ~/.eden so rm -rf ./eden removes everything including the config. Also this way we don't mix eden installations and do not have any stale artifacts. 
Also this way it's much easier to debug what happens&

**Comment by rvs** [comment]
Big +1 to this!

**Comment by mydatascience** [comment]
Outdated as an issue. Right now we are satisfied with the behavior
