### ISSUE TITLE
Fix local Registry

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#278]
Docker Image from Local Registry
eden starts a local registry image, running on the localhost at port 5000 (configurable). You can start a docker image from that registry by passing it the --registry=local option. The default for --registry is the hostname given by the registry. For example, docker://docker.io/library/nginx defaults to docker.io. But if you pass it the --registry=local option, it will try to get it from the local, eden-managed registry.

eden pod deploy --registry=local docker://nginx

Doesn't work @deitch

**Comment by mydatascience** [comment]
```
jenkins@jenkins-eden:~/workspace/eve-docker-image$ ./eden pod deploy --registry=local docker://nginx
Error: unknown flag: --registry
Usage:
```

**Comment by deitch** [comment]
Yeah, never got to that part. Let's keep this issue open as a tracking issue.

**Comment by mydatascience** [comment]
Done. We even have a test on that
