### ISSUE TITLE
Create ./eden pod publish

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#279]
Make the command that allows publish the vm's to dockerhub  like [edge-containers](https://github.com/lf-edge/edge-containers) 
Support docker pod deploy for the containers with manifest parsing without any additional param required

Examples:
`./eden pod publish --registry local --file <edge-container config> ` -publishes container to local docker registry 
`./eden pod publish http://cdimage.debian.org/cdimage/openstack/current/debian-10.4.3-20200610-openstack-amd64.qcow2 ` -publish vm as an edge-container to dockerhub

**Comment by rvs** [comment]
Yup -- that would be very helpful

**Comment by mydatascience** [comment]
ok we have it
