### ISSUE TITLE
infowatch and logwatch commands should be made into options of info and log

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#28]
There's no reason to have separate infowatch and logwatch commands. Those should be made into `-f` flag of info and log respectively.

**Comment by deitch** [comment]
Definitely. When I first moved them from separate CLIs into sub commands of `eden`, I wanted to do it, but figured someone who knows the differences might do it better.

**Comment by sadov** [comment]
Fixed on [PR43](https://github.com/lf-edge/eden/pull/43).

**Comment by mydatascience** [comment]
We removed these `infowatch` and `logwatch`

**Comment by rvs** [comment]
Cool closing now
