### ISSUE TITLE
eden clean times out

### ISSUE THREAD

**Issue by eriknordmark** [lf-edge/eden#280]
This sequence of stop then clean used to work.
Now clean is trying to talk (to someone?) - ''Hello, is anybody out there?" by Pink Floyd?

nordmark@bobo:~/master/eden$ ./eden stop
INFO[0000] adam stopped                                 
INFO[0001] redis stopped                                
INFO[0001] registry stopped                             
INFO[0002] eserver stopped                              
INFO[0002] EVE stopped                                  
nordmark@bobo:~/master/eden$ ./eden clean
INFO[0000] Cleanup current context                      
INFO[0000] Attempt to re-establish connection (0) of (20) 
INFO[0005] Attempt to re-establish connection (1) of (20) 
INFO[0010] Attempt to re-establish connection (2) of (20) 
INFO[0015] Attempt to re-establish connection (3) of (20) 
INFO[0020] Attempt to re-establish connection (4) of (20) 
INFO[0025] Attempt to re-establish connection (5) of (20) 
INFO[0030] Attempt to re-establish connection (6) of (20) 
INFO[0035] Attempt to re-establish connection (7) of (20) 
INFO[0040] Attempt to re-establish connection (8) of (20) 
INFO[0045] Attempt to re-establish connection (9) of (20) 
INFO[0050] Attempt to re-establish connection (10) of (20) 
INFO[0055] Attempt to re-establish connection (11) of (20) 
INFO[0060] Attempt to re-establish connection (12) of (20) 
INFO[0065] Attempt to re-establish connection (13) of (20) 
INFO[0070] Attempt to re-establish connection (14) of (20) 
INFO[0075] Attempt to re-establish connection (15) of (20) 
INFO[0080] Attempt to re-establish connection (16) of (20) 
INFO[0085] Attempt to re-establish connection (17) of (20) 
INFO[0090] Attempt to re-establish connection (18) of (20) 
INFO[0095] Attempt to re-establish connection (19) of (20) 
FATA[0100] unable to send request: all connection attempts failed 

Did it actually clean up? Apparently not.

**Comment by deitch** [comment]
Sort of a follow-on to #251, where eden used to clean fully, then partially. Now it doesn't work.

**Comment by mydatascience** [comment]
#282

**Comment by mydatascience** [comment]
@eriknordmark May I close it?

**Comment by mydatascience** [comment]
Please feel free to reopen
