### ISSUE TITLE
Generate certs fails but pretend it succeeded

### ISSUE THREAD

**Issue by eriknordmark** [lf-edge/eden#281]
Do I have to rm -rf and restart with docker pull each time??

Tried a eden clean then eden stop. Succeds.
Then starting over:

nordmark@bobo:~/master/eden$ ./eden config add default
nordmark@bobo:~/master/eden$ ./eden config set default --key eve.tag --value=0.0.0-emerg-ed3648e9-dirty-2020-09-24.22.55
INFO[0000] Current context is: default                  
nordmark@bobo:~/master/eden$ ./eden setup
INFO[0000] GenerateEveCerts run: /home/nordmark/master/eden/dist/bin/eden-linux-amd64 utils certs --certs-dist=/home/nordmark/master/eden/dist/default-certs --domain=mydomain.adam --ip=192.168.10.45 --eve-ip=192.168.10.45 --uuid=effab974-e8be-4811-ad10-5ea7c8fcddd7 --ssid= --password= -v info 
FATA[0002] cannot parse key from %s: %s/home/nordmark/master/eden/dist/certs/root-certificate-key.pemasn1: structure error: tags don't match (16 vs {class:0 tag:13 length:45 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2 
ERRO[0002] cannot GenerateEveCerts: exit status 1       
INFO[0002] GenerateEVEConfig done                       
INFO[0003] cannot pull lfedge/eve-uefi:0.0.0-snapshot-master-d7206d73-amd64 
INFO[0003] will retry with lfedge/eve-uefi              
INFO[0003] Extract layer 3413be8830ef7b4871c1459953be20c38a582b80b4422603067ad07a5a9244e3/layer.tar 
INFO[0003] Extract layer 42abb96a9111fbdd082bc36da8396b25e816e17168fb4783264d7bc2796af9fe/layer.tar 
INFO[0003] Extract layer c5dbaf04b9104f6ece8e2800321cedeacb677e3546637b9791229f57fcade63b/layer.tar 
INFO[0023] download EVE done: /home/nordmark/master/eden/dist/default-images/eve/live.img 
nordmark@bobo:~/master/eden$ ./eden start
INFO[0000] started container: b87aa6092b4c8361f2c66c242e19b221aa6068d571009a8285b2ba0215370938 
INFO[0000] Redis is running and accessible on port 6379 
INFO[0000] started container: 56cb4193b1727fd6b56a645a51a9cfc59de85dfc69601e0e14a7cb8ce278c7d5 
INFO[0000] Adam is running and accesible on port 3333   
INFO[0001] started container: dd6661209207bd175270a9a6c86128243c68a19ce89eb56f3bb3a87d411d74e7 
INFO[0001] registry is running and accesible on port 5000 
INFO[0002] started container: 44cc4cc9493bea58386347169d2859831b640964c57e93a64cc1b2a5259c0deb 
INFO[0002] Eserver is running and accesible on port 8888 
INFO[0002] StartEVEQemu run: /home/nordmark/master/eden/dist/bin/eden-linux-amd64 eve start --qemu-config=/home/nordmark/.eden/default-qemu.conf --eve-serial=31415926 --eve-accel=true --eve-arch=amd64 --eve-os=linux --eve-log=/home/nordmark/master/eden/dist/eve.log --eve-pid=/home/nordmark/master/eden/dist/eve.pid --image-file=/home/nordmark/master/eden/dist/default-images/eve/live.img -v info 
INFO[0000] Start EVE: qemu-system-x86_64 -display none -serial telnet:localhost:7777,server,nowait -nodefaults -no-user-config -smbios type=1,serial=31415926 -machine q35,accel=kvm,dump-guest-core=off -cpu host,invtsc=on,kvmclock=off -machine kernel-irqchip=split -device intel-iommu,intremap=on,caching-mode=on,aw-bits=48 -drive file=/home/nordmark/master/eden/dist/default-images/eve/live.img,format=qcow2 -readconfig /home/nordmark/.eden/default-qemu.conf  
INFO[0000] With pid: /home/nordmark/master/eden/dist/eve.pid ; log: /home/nordmark/master/eden/dist/eve.log 
INFO[0002] EVE is starting                              
nordmark@bobo:~/master/eden$ ./eden eve onboard
FATA[0000] unable to read server CA file at /home/nordmark/master/eden/dist/default-certs/root-certificate.pem: open /home/nordmark/master/eden/dist/default-certs/root-certificate.pem: no such file or directory

**Comment by mydatascience** [comment]
https://github.com/lf-edge/eden/pull/282

**Comment by mydatascience** [comment]
I think this is fixed
