### ISSUE TITLE
Run Windows VM image in eve and make sure virtio-ioMMU on GPU works 

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#288]
Make sure Windows image runs and GPU is available inside

**Comment by vshebordaev** [comment]
I managed to get physical VGA signal from ASPEED controller on my VM running Windows 10 Pro at my home Intel Xeon 1270 v3. Sure, I had to apply ACS override patch and pass through the controller to VM then.

What the Windows image should I run and what the GPU make work?

**Comment by rvs** [comment]
Btw ACS override just [re-]landed in EVE https://github.com/lf-edge/eve/pull/1685 -- hence you should get this by default with latest EVE tag 5.17.0

**Comment by mydatascience** [comment]
we have it done
