### ISSUE TITLE
Eden eve ssh <command> grabs all the out stream

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#296]
E.g. 
`./eden eve ssh "echo 'hello' > 1.txt"` does not create a local 1.txt, but rather outputs `'hello' > 1.txt
` to console.
This limits usage of eden eve ssh for perf profiling

**Comment by giggsoff** [comment]
Seems, that we need to use `./eden eve ssh "echo 'hello'">1.txt`. But you are right, we need to remove the garbage string 
```
giggsoff@giggsoff-PC:~/itmoeve/githubeden$ cat 1.txt 
time="2020-10-05T20:35:51+03:00" level=info msg="Try to ssh 127.0.0.1:2222 with key /home/giggsoff/itmoeve/githubeden/dist/default-certs/id_rsa"
hello
```

**Comment by mydatascience** [comment]
No no ... I wanna this to create 1.txt on EVE not where I run the command. 
Otherwise yesI will run `/eden eve ssh "echo 'hello'">1.txt`

**Comment by giggsoff** [comment]
@mydatascience please try
`echo "hello"|./eden eve ssh 'tee 1.txt'`

**Comment by rvs** [comment]
FWIW @mydatascience @giggsoff -- I'm going to change that whole area os how ssh done in EVE later this week -- so all that pain is expected to go away.

**Comment by mydatascience** [comment]
I'm ok now
