### ISSUE TITLE
eden config should be decoupled from setup operations

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#30]
eden config should remain as a command that allows me to manipulate config files for various pieces of the harness (global eden config, configs for adam, eve and eserver) and thus never block at trying to download/unpack anything.

All the functionality that has to do with "setting things up" (like downloading images from docker hub, building images, etc.) should be moved into a standalone command called setup.

Once we split it this way `eden config` will stop at making sure that various config files in the filesystem are the way I like them but *NOT INTERPRET* those configs. IOW, if an image I pointed at in my config is missing and needs to be downloaded -- `eden config` will not attempt to do that).

On the other hand, the new `eden setup` command will treat all the various configs produced by `eden config` as R/O and will be in business of making sure that my system is setup according to the values in those configs (images are downloaded, or built, etc., etc.). It will be important to make sure that `eden setup` has a dry run option. So that running `eden setup --dry-run` will produce an output of what `eden setup` would do

**Comment by sadov** [comment]
Fixed on [PR43](https://github.com/lf-edge/eden/pull/43).
