### ISSUE TITLE
Deploy docker image centos-vnc on MacOS Big Sur 

### ISSUE THREAD

**Issue by dautovri** [lf-edge/eden#346]
MacOS Big Sur 

# Docker - Docker Image with Centos + VNC
```
docker run -it --rm -e password='21042104' -p 5901:5901 labeg/centos-lxqt-vnc
```
it's working if you run on docker 

![Screen Shot 2020-11-02 at 6 48 03 PM](https://user-images.githubusercontent.com/4597187/97888430-2f13c480-1d3c-11eb-86cd-33f4691d157e.png)

# Eden - Docker Image with Centos + VNC
```
./eden pod deploy -p 8027:22 docker://labeg/centos-lxqt-vnc --vnc-display=1 --memory=2GB --cpus=2 --metadata=‘password=21042104’ --volume-type=oci 
```
But it's HALTED  on eden   

```
./eden pod ps 

HALTED: [description:“failed to update OCI spec from volume /persist/vault/volumes/d95f1ac
1-501d-494e-bfff-76835fd2ee82#0.container (no users found)” timestamp:{seconds:1604328813 nanos:428045152}]
```

**Comment by rvs** [comment]
This seems like it doesn't have much to do with Eden and a lot to do with how `labeg/centos-lxqt-vnc` is structured -- I suggest you dig into `labeg/centos-lxqt-vnc` implementation and report back what you find.

**Comment by dautovri** [comment]
Tested on several other docker images and VNC works. I am closing the issue, because not related to Eden.
