### ISSUE TITLE
need to configure ssh access in EVE

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#35]
it appears that ssh is disabled by default in a running instance of EVE -- we need to enable it via sending an appropriate part of the config via adam (e.g. https://github.com/lf-edge/eve/blob/master/docs/FAQ.md#1-how-to-ssh-into-a-running-instance-of-eve)

**Comment by giggsoff** [comment]
This code already exists in Eden:
https://github.com/lf-edge/eden/blob/8102f10a8175ff4e00d655d03d23ef73d7191c9c/pkg/controller/device.go#L232-L237

At the moment, ssh key loading is performed at any configuration loading, for example, at step test_controller.

**Comment by sadov** [comment]
Fixed on [PR43](https://github.com/lf-edge/eden/pull/43).
