### ISSUE TITLE
Need more informative errors from eden when there are test failures

### ISSUE THREAD

**Issue by eriknordmark** [lf-edge/eden#351]
# Description

As part of running the github actions for EVE which kicks of some tests using Eden, if there are any failures the output does not indicate much useful. See for example https://github.com/lf-edge/eve/pull/1611/checks?check_run_id=1360269311

Re-running the tests makes it pass, but it would be good to have the test output indicate that was wrong where, whether that is in the form of logs indicating how far the test got, and/or by providing more information about the state of things when the failure happened.

# Steps to Reproduce

Watch the EVE PRs fail from time to time; this seems to happen on more every third to every fifth PR which is running the Eden tests.

# Actual Results

# Expected Results

# Additional Information

**Comment by mydatascience** [comment]
Totally agree. We are aware and consider this a priority. Will at least report `eden pod ps` and `eden status` once tests fail

**Comment by rvs** [comment]
Super +1 to @eriknordmark comments and here's an additional from myself -- it would be really nice if Eden test run can output results in a format compatible with JUnit, etc. -- we're using the same format for our unit test in EVE and this allows us to use this GitHub Action plugin to report these results as annotations https://github.com/lf-edge/eve/blob/master/.github/workflows/eve.yml#L19

It would be really helpful if Eden can do the same @mydatascience

**Comment by mydatascience** [comment]
I believe I can close it for now. Please reopen if it's still an issue
