### ISSUE TITLE
need to proxy adam commands via eden

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#36]
I need to be able to use eden to issue adam commands as per: https://github.com/lf-edge/adam

Here's what I need to be able to do:

```
eden adam onboard -> adam admin onboard
eden adam device -> adam admin device
```

NOTE1: that these need to be proxied in such a way that they work out of the box (IOW, I don't have to manually specify --server, etc. etc.)

NOTE2: onboad command needs to have reasonable defaults so I don't have to specify --path ../certs/onboard.cert.pem --serial 31415926)

**Comment by mydatascience** [comment]
I suggest to have it as eden adam exec ... <any adam command supported by API>

**Comment by mydatascience** [comment]
any thoughts @rvs

**Comment by deitch** [comment]
I think that would be fine, as long as it is one-shot commands (i.e. don't have `eden adam exec` open some strange interactive shell).

**Comment by rvs** [comment]
+1 to what @deitch is saying @mydatascience -- any chance you guys can bump a priority on this?

**Comment by mydatascience** [comment]
@rvs do we still need it?

**Comment by rvs** [comment]
Lets close it for now
