### ISSUE TITLE
eden status need to display whether EVE instance is in the unknown, onboarding or managed state

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#37]
Currently an EVE instance under Eden's management can be in one of the following states:
   * unknown
   * onboarding
   * managed

These would correspond to the status of the adam admin device/onboard commands and need to be displayed by `eden status`

**Comment by mydatascience** [comment]
Let' close this

**Comment by rvs** [comment]
Do you think that output is not particular useful or it belongs to a different subcomand?

**Comment by mydatascience** [comment]
I put your comment into #41. This all relates to "Change output of status command"

**Comment by rvs** [comment]
Aha! Makes sense!
