### ISSUE TITLE
Command "eden eve onboard" doesn't work

### ISSUE THREAD

**Issue by mperov** [lf-edge/eden#380]
## Description

I got the problem on Quickstart which is described in README.md.
This problem is on command `./eden eve onboard`.

## Steps to Reproduce

```
git clone https://github.com/lf-edge/eden.git
cd eden
make clean
make build
eden config add default
eden setup
eden start
eden eve onboard
```

## Actual Results
```
eden$ ./eden eve onboard
INFO[0000] Adam waiting for EVE registration (0) of (20) 
INFO[0020] Adam waiting for EVE registration (1) of (20) 
INFO[0040] Adam waiting for EVE registration (2) of (20) 
INFO[0060] Adam waiting for EVE registration (3) of (20) 
INFO[0080] Adam waiting for EVE registration (4) of (20) 
INFO[0100] Adam waiting for EVE registration (5) of (20) 
INFO[0120] Adam waiting for EVE registration (6) of (20) 
INFO[0140] Adam waiting for EVE registration (7) of (20) 
INFO[0160] Adam waiting for EVE registration (8) of (20) 
INFO[0180] Adam waiting for EVE registration (9) of (20) 
INFO[0200] Adam waiting for EVE registration (10) of (20) 
INFO[0220] Adam waiting for EVE registration (11) of (20) 
INFO[0240] Adam waiting for EVE registration (12) of (20) 
INFO[0260] Adam waiting for EVE registration (13) of (20) 
INFO[0280] Adam waiting for EVE registration (14) of (20) 
INFO[0300] Adam waiting for EVE registration (15) of (20) 
INFO[0320] Adam waiting for EVE registration (16) of (20) 
INFO[0340] Adam waiting for EVE registration (17) of (20) 
INFO[0360] Adam waiting for EVE registration (18) of (20) 
INFO[0380] Adam waiting for EVE registration (19) of (20) 
FATA[0400] onboarding timeout. You may try to run 'eden eve onboard' command again in several minutes. If not successful see logs of adam/eve
```

## Additional Information

Log file dst/eve.log has something like this:

```
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize kvm: Permission denied
```

I found two ways to solve this problem:

1) Run command with sudo permission but it isn't good idea;
2) Add $USER to kvm group.

I think README.md should has information about it.

OS Linux Ubuntu 18.04

**Comment by rvs** [comment]
Well @mperov -- it seems like you solved your problem (and yes I believe adding $USER to kvm group is the right solution). I will leave it to @mydatascience to add this step to the README for Linux (note thought that most of our developers are on Mac OS X and hence Linux is a less tested platform for development).

Finally, you DO have an option of not enabling acceleration at all (and thus no need to have access to KVM) -- you simply need to tweak that in your eden config (e.g. `eden config edit` and then look for section `eve` and knob called `accel`).

**Comment by mperov** [comment]
Thx for your answer. I will try to config using `eden config edit`

**Comment by mydatascience** [comment]
Add $USER to kvm group.
This is exactly that solves it.

**Comment by mperov** [comment]
All informations are added to README, so I close issue.
