### ISSUE TITLE
"eden start" doesn't work

### ISSUE THREAD

**Issue by mperov** [lf-edge/eden#383]
## Description

I got problem when start eden using `eden start`. I didn't see some problems in log output. About it I reported #382.

## Steps to Reproduce
```
git clone https://github.com/lf-edge/eden.git
cd eden
make clean
make build
eden config add default
eden setup
eden start
```

## Actual Results
```
$ cat dist/eve.log
qemu-system-x86_64: -device intel-iommu,intremap=on,caching-mode=on,aw-bits=48: Property '.aw-bits' not found
```

## Additional Information

I solved it when I deleted option `aw-bits=48` from 100 line in `pkg/defaults/defaults.go`.
I didn't find some requirements about QEMU in README so I only installed QEMU from Ubuntu repo. Maybe is there something requirements?

OS Linux Ubuntu 18.04
Version of QEMU is **2.11.1**.

**Comment by rvs** [comment]
I guess this is related to you using older qemu and can be closed now?

**Comment by mperov** [comment]
Yes, thx!
