### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by giggsoff** [lf-edge/eden#430]
Seems, that we need to do refactoring of our code

- [x] We should remove nested calls to cmd from pkg: [example](https://github.com/lf-edge/eden/blob/master/pkg/eden/eden.go#L340-L341)
- [x] We should create abstraction of devModel (qemu/gcp/rpi/common) with image preparation, configuration, start/stop functions. Now we can find it in many places and it is quite difficult to add new one (parallels).
- [x] We should move all we need for Eden into dist, now we have dist and tests in release, it is misleading.
- [x] We should improve configuration of tests via environment variables.

**Comment by sadov** [comment]
Yes, I agree with that. Some comments about last item. Currently, for each line in the `eden test` test script, some parameters are automagically added to match its own parameters. When we only used our test binaries it worked well, but now we want to use any external programs in our scripts and they can get confused by such extra options. Seems reasonable to move a part of params handling logic to env. vars.

**Comment by giggsoff** [comment]
#441

**Comment by giggsoff** [comment]
#450
