### ISSUE TITLE
Standalone eden adam start fails

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#46]
Seems to be related to the Adam run path not existing:

```
eden adam start
INFO[0000] Executable path: /Users/roman/src/lfe/eden/eden
INFO[0001] {"status":"Pulling from lfedge/adam","id":"0.0.26"}
INFO[0001] {"status":"Digest: sha256:b506a8e4cad7f97b74425bcddbc00ae966b03232fedfe9d76dd1fd90931b6899"}
INFO[0001] {"status":"Status: Downloaded newer image for lfedge/adam:0.0.26"}
ERRO[0001] cannot start adam: error in create adam container: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/roman/eden/adam/run
```

If I make it manually `mkdir -p /Users/roman/eden/adam/run` it seems to work

**Comment by giggsoff** [comment]
For now, directory ```~/eden/adam/run/adam``` is created by ```eden setup``` and contains server-key.pem  and server.pem. ```server.pem``` is used on step of modification of EVE live image.
So, before calling the command ```eden adam start``` was supposed to call ```eden setup```.

**Comment by rvs** [comment]
Sure, but why didn't CLI tell me that? @giggsoff

**Comment by sadov** [comment]
Fixed at [PR50](https://github.com/lf-edge/eden/pull/50)
