### ISSUE TITLE
USB passthrough

### ISSUE THREAD

**Issue by sadov** [lf-edge/eden#466]
# Description

[USB passthrough](https://github.com/lf-edge/eden/blob/246ce0008890f9def8087ded56dee15a77c3bcf2/docs/usb-pt.md) doesn't work for me.

# Steps to Reproduce

1. Create image file for USB-stick emulation, for ex. `/tmp/stick.img`.
2. Append USB-stick description to `~/.eden/default-qemu.conf`:
```
[drive "stick"]
  if = "none"
  file = "/tmp/stick.img"
  format = "raw"

[device "xhci"]
  driver = "nec-usb-xhci"

[device]
  driver = "usb-storage"
  bus = "xhci.0"
  drive = "stick"
```
3. Restart EVE:
```
eden eve stop
eden eve start
```
4. Log into EVE with `eden eve console` and check for an emulated USB stick with` fdisk -l` and `lsusb`:
```
# fdisk -l
...
Disk /dev/sdb: ...
...
# lsusb 
...
Bus 004 Device 002: ID 46f4:0001
...
```
5. Deploy application accordingly bus an device numbers from `lsusb`:
```
eden pod deploy -p 8027:22 https://cloud-images.ubuntu.com/releases/groovy/release-20201022.1/ubuntu-20.10-server-cloudimg-amd64.img      -v debug --metadata='#cloud-config\npassword: passw0rd\nlock_passwd: False\nchpasswd: { expire: False }\nssh_pwauth: True\n' --adapters USB4:2
```

# Actual Results

```
$ eden pod ps
NAME		IMAGE						UUID					INTERNAL	EXTERNAL	MEMORY	STATE(ADAM)	LAST_STATE(EVE)
eager_wozniak	eserver/ubuntu-20.10-server-cloudimg-amd64.img	cb7efef7-c087-476b-bdff-ff1a76d22acb	10.1.0.2:22	127.0.0.1:8027	0 B/0 B	IN_CONFIG	HALTED: [description:"unknown adapter 2 USB4:2" timestamp:{seconds:1609318015 nanos:952024524}]
```

# Expected Results

The application must be in the RUNNING state, the emulated USB flash drive must be accessible from the application.

# Additional Information

Ubuntu 20.04.1 LTS

qemu-system-x86 1:4.2-3ubuntu6.10

EDEN commit 54873ab5156c01efb36493ee3d20b16ed403a93a

**Comment by giggsoff** [comment]
Seems, that we need to modify code of our qemu model. 
Please, take a look at #467. I also added there automatization of usb-storage device connection.

**Comment by sadov** [comment]
Seems work.
