### ISSUE TITLE
Need to create an eden controller subcommand

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#51]
After some playing with Eden it has become clear to me that we need an `eden controller` subcommand that should be modeleted after zcli CLI API but capable of operating on the following controllers:
   * plain text files containing JSON EVE config
   * binary files containing protobuf serialization of the EVE config
   * Adam controller
   * Zedcloud

The way I envision this command is the following:

```
   eden controller -m [file|proto|adam|zedcloud]://<URL> [subset of zcli commands]
```

The semantics here is going to be that for plain text files, binary files and Adam controller the above command will simply take the source file from the -m option, parse it, apply the changes requested by zcli commands and store the result back (obviously in Adam's case that config needs to be retrieved via Adam's admin endpoint first and then submitted to that same endpoint -- but otherwise Adam use case is exactly like operating on a local JSON config).

To get us going, I suggest we only focus on plain text files with JSON config and Adam for now (but obviously the implementaion need to be designed in such a way that we can plug the other two easily later on).

And here's the first zcli command we need to implement `edge-node`. Hence the request here is for:

```
 edge-node reboot [-f] <name>
 edge-node update <name> [--title=<title>] [--lisp-mode=experimental|default] [--project=<project>] [--clear-onboarding-certs] [--config=<key:value>...] [--network=<network>...]
 edge-node eveimage-update <name> --image=<image> [--activate]
 edge-node eveimage-remove <name> --image=<image>
```

**Comment by deitch** [comment]
I am not sure I understand. Is the goal here to be able to tell a controller to update the config for a device, etc.? i.e. tell it to take actions?

What is the `file` or `json` or whatever mode for? Or do these really mean, "I would want to change the config for a device to tell it to do X, but rather than doing it manually, I want a convenient CLI that updates a standard config"?

**Comment by rvs** [comment]
Hey @deitch 

> I am not sure I understand. Is the goal here to be able to tell a controller to update the config for a device, etc.? i.e. tell it to take actions?

Correct. The way to think about it is this: at the end of the day the raison d'être of any controller is to build a config for EVE. That's where everything bottoms out. Controller builds that config based on the actions that are performed via API calls of controller itself. Those API calls are wrapped in zcli commands that we're modeling here.

However, in case of `-m file|proto|adam` -- there's no controller and no API calls to the controller. There's simply a config before and a config after a zcli-like command was applied. We're just cutting middle man out (controller) and operating on config directly while using exactly the same zcli commands that would've operated on the config via controller.

> What is the file or json or whatever mode for? Or do these really mean, "I would want to change the config for a device to tell it to do X, but rather than doing it manually, I want a convenient CLI that updates a standard config"?

Or better yet -- rather than asking a controller indirectly -- I'm simply recording the change in the config.

**Comment by rvs** [comment]
Hey @sadov @giggsoff @deitch -- this issue came up in a related discussion so I wanted to make sure that we're all on the same page as to what I'd like to demo next Tue during our sprint demos (this will be executed out of my EVE workspace -- asumin eden command is pre-built and available in my PATH):

```
make HV=kvm rootfs
eden config
eden setup
eden start
eden eve onboard
eden controller -m adam://  edge-node update UUID --config="debug.enable.ssh:`cat .ssh/id_rsa.pub`"
eden controller -m adam://  edge-node eveimage-update --image=dist/arch64/installer/rootfs.img
eden controller -m adam://  edge-node eveimage-update --image=dist/arch64/installer/rootfs.img --activate
```

We can even assume that `-m adam://` is the default for now and thus simplify the last few commands.

**Comment by sadov** [comment]
OK -- we started development on this branch:
https://github.com/itmo-eve/eden/tree/controller

**Comment by deitch** [comment]
> However, in case of -m file|proto|adam -- there's no controller and no API calls to the controller. There's simply a config before and a config after a zcli-like command was applied. We're just cutting middle man out (controller) and operating on config directly while using exactly the same zcli commands that would've operated on the config via controller.

That is what I am trying to get at. So what you mean is, "I want a cli to manipulate eve config files." They might not actually be "files", they might be streams or something else, but that is the basic idea. zcli talks directly to zedcloud, so it is too much (and has too many dependencies) for this.

**Comment by deitch** [comment]
If I understood you correctly, I have wanted that for a long time. Adam's Achilles heel is that you have to edit the config manually. 

The question is, should we implement this in eden? Or in adam and expose a library surface? Either would work, but what is the "right place" to do it?

**Comment by rvs** [comment]
Well @deitch  the top-line functionality belongs to Eden. IOW, with Eden I want to be able to work seamlessly with 3 types of controllers (files, Adam and zedcloud) without thinking too much about how Eden maps my commands to API calls or file updates.

So I'd say -- let it stew in Eden for now -- and later on we can see if we can librarify some of this or even hang off of Adam's admin APIs.

**Comment by deitch** [comment]
That is a good way of looking at it. Actually, I really would like some code somewhere to "own" manipulating the config json, and then the rest of these can consume them as a library.

**Comment by sadov** [comment]
Implemented on [PR56](https://github.com/lf-edge/eden/pull/56)

**Comment by rvs** [comment]
Good job @sadov @giggsoff -- closing the issue now -- will open new one for additional functionality
