### ISSUE TITLE
We don't allow applications to listen on several interfaces and don't tell that to the user

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#515]
Current behavior: 
If we have a host device with 2 network interfaces and then create a VM: 
    a) We see 1 network interface on VM (which is ok)
An application is available on only ONE physical interface. (first) 

Expected behavior: 

We expect to be able to pass the config for the application to be available on BOTH interfaces and in general  be able to config the interfaces passed to the application

**Comment by rvs** [comment]
I guess I'm not quite sure I understand the use case here, can you please ellaborate?

**Comment by mydatascience** [comment]
If you launch a VM or a container (say eden pod deploy)  you will not by default listen on all available interfaces 
So say you have wifi and eth. The app / VM will listen only on one of them.

**Comment by rvs** [comment]
This maybe more appropriate as an issue for EVE then

**Comment by mydatascience** [comment]
closing. we made an option to specify the interface to listen at
