### ISSUE TITLE
USB disappears after VM reboot 

### ISSUE THREAD

**Issue by dautovri** [lf-edge/eden#578]
# Description
```
HV = Xen 
Ubuntu 20.04 
```

1) Sometimes app stuck in HALTED state
HALTED: [description:"one of the application's tasks has crashed - please restart application instance" timestamp:{sec onds:1617267653 nanos:68552285}]
2) Test is not passing because USB disappears. (repeatable)

# Steps to Reproduce
How to repeat the test:

```
make build-tests
./eden config add
./eden config set default --key eve.hv --value xen
./eden setup
./eden start && ./eden eve onboard 
./dist/bin/qemu+usb.sh 
./dist/bin/eden+ports.sh 2223:2223
./eden eve stop 
./eden eve start 
./eden test tests/hardware_reboot -v debug 
```
# Actual Results
```
[diff -before_reboot +after_reboot]
         ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o PasswordAuthentication=no -i /home/r/GolandProjects/eden/dist/tests/eclient/image/cert/id_rsa -p 8027 ubuntu@192.168.31.226 lsusb
        -Bus 001 Device 002: ID 46f4:0001 QEMU QEMU USB HARDDRIVE
         Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
        FAIL: testdata/hardware_usb_reboot.txt:41: before_reboot and after_reboot differ
```

xenstore-ls output from @giggsoff :
Before reboot: 
```
vusb = ""
    0 = ""
     type = "devicemodel"
     usb-ver = "2"
     num-ports = "6"
     port = ""
      1 = "2-1"
      2 = ""
      3 = ""
      4 = ""
      5 = ""
      6 = ""
```
After reboot:

```
   vusb = ""
    0 = ""
     type = "devicemodel"
     usb-ver = "2"
     num-ports = "6"
     port = ""
      1 = ""
      2 = ""
      3 = ""
      4 = ""
      5 = ""
      6 = ""
```
Logs from @sadov [Logs](https://github.com/lf-edge/eden/files/6244484/hardware_reboot.001.log)

# Expected Results
List of USB devices lsusb  should be the same before and after reboot.

**Comment by sadov** [comment]
@dautovri pls. check the "Steps to Reproduce" carefully:
```
$ make build-test 
make: *** No rule to make target 'build-test'.  Stop.
```

**Comment by zed-sadov** [comment]
Similarly tested for COM pass-through:
https://github.com/lf-edge/eden/pull/579
Settings remain the same after reboot.
Results are the same as for client as for ubuntu image on – USB pass-through settings are lost after reboot, COM-port settings are retained.

**Comment by sadov** [comment]
Similarly tested for COM pass-through:
https://github.com/lf-edge/eden/pull/579
Settings remain the same after reboot.
Results are the same as for eclient as for ubuntu image on – USB pass-through settings are lost after reboot, COM-port settings are retained.

**Comment by dautovri** [comment]
> Similarly tested for COM pass-through:
> #579
> Settings remain the same after reboot.
> Results are the same as for eclient as for ubuntu image on – USB pass-through settings are lost after reboot, COM-port settings are retained.

I checked [PR579](https://github.com/lf-edge/eden/pull/579) as well. I can confirm that Xen + Ubuntu VM retain COM port after reboot(` sudo shutdown -r +1 `).
