### ISSUE TITLE
EVE does not get IP after it was installed via IPXE

### ISSUE THREAD

**Issue by srivatsanv1991** [lf-edge/eden#582]
# Description
Deploy EVE on a VM through ipxe. Though I am able to install EVE via ipxe with dhcp enabled. 
EVE does not get IP address from Dhcp after the installation.

Tried to assign static IP address to EVE by placing global.json at `conf/Deviceportconfig` directory

EVE does not get IP from the Dhcp server or use the static IP Address Configuration

# Steps to Reproduce
## IPXE Boot
Clone Eden repo
`./eden config add default --devmodel=general`
`./eden config set default --key adam.eve-ip --value IP`
`./eden config add default --devmodel=general --netboot=true`

Copy the `ipxe.efi.cfg` generated at `dist/default-images/eve/tftp/` to your tftp path on the PXE Server
Boot the config from there.

Enable Dhcp on the PXE Server. So when the VM is powered on it goes to Netboot, gets IP from PXE server and then the ipxe.efi.cfg is loaded to it.

## Assigning Static IP Address to EVE
Clone Eden repo
`./eden config add default --devmodel=general`
`./eden setup --eve-config-dir <dir_containing_global.json>`

On the EVE Machine
`cp /config/global.json /config/DevicePortConfig`
`rm /config/DeviPortConfig/override.json.template`
Restart EVE

Global.json with static IP Address for eth0
`{
    "Version": 1,
    "Ports": [
        {
            "AddrSubnet": "x.x.x.x/24",
            "Dhcp": 1,
            "DnsServers": [
                "x.x.x.x"
            ],
            "DomainName": "",
            "Free": true,
            "Gateway": "x.x.x.x",
            "IfName": "eth0",
            "Name": "Management1",
            "IsMgmt": true,
            "NtpServer": "",
            "NetworkProxyEnable": false,
            "NetworkProxyURL": "",
            "NtpServer": "",
            "Pacfile": "",
            "Proxies": null
        },
        {
            "Dhcp": 4,
            "Free": true,
            "IfName": "eth1",
            "Name": "Management2",
            "IsMgmt": true
        }
    ]
}`

# Actual Results
## IPXE Boot
The VM gets IP Address from the PXE Server. But the EVE does not get IP Address once it is installed on the VM
![image (2)](https://user-images.githubusercontent.com/32692016/113828175-ad2a3a80-97b6-11eb-9a1b-ae37c15eac1d.png)

## Assigning Static IP Address to EVE
The IP Address is assigned to the EVE on eth0 but is unable to ping the Eden machine which is on the same network, unable to assigned the IP Address as shown below.
![image (1)](https://user-images.githubusercontent.com/32692016/113828124-a0a5e200-97b6-11eb-993c-bb9db43d7c55.png)
![image](https://user-images.githubusercontent.com/32692016/113829154-bd8ee500-97b7-11eb-8259-d1fd6b70daad.png)
![image](https://user-images.githubusercontent.com/32692016/113829303-eadb9300-97b7-11eb-9144-8b15e5610b14.png)

Unable to onboard EVE from Eden.
INFO[0000] Attempt to re-establish connection (0) of (20)
INFO[0005] Attempt to re-establish connection (1) of (20)
INFO[0010] Attempt to re-establish connection (2) of (20)
.
.
FATA[0100] unable to send request: all connection attempts failed

# Expected Results
## IPXE Boot
EVE should get the IP Address from the Dhcp (PXE Server)

## Assigning Static IP Address to EVE
EVE to use the static IP address from the global.json. Onboard EVE from Eden.

# Additional Information

**Comment by rvs** [comment]
Hey @srivatsanv1991 -- this is correct behavior of EVE. What you're seeing is not related to the lack of IP address, but rather the lack of controller. You can read up more on the controller here https://github.com/lf-edge/eve/tree/master/docs#eve-controller and try using Eden as your controller https://github.com/lf-edge/eden#raspberry-pi-4-support . Finally, if you'd like to give one of the commercial controllers a try -- ping me on Slack.
