### ISSUE TITLE
Improve efficiency of Makefile cloning and building of EVE

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#6]
Right now Makefile logic does two parallel clones of EVE into `dist/evebaseos` and `dist/eve`. 

I understand why are you doing it -- since you want to use these two repositories for two different purposes -- one is running live image of EVE under test and the other one for building a baseos image when you need it for baseos-level testing.

In order to save time and bandwidth, lets:
   1. just clone repository once into `dist/eve`
   2. run `make build-tools`
   3. create `dist/evebaseos` and `dist/evelive` as local git clones `git clone eve evelive`
   4. copy (or symlink) `dist/eve/build-tools/bin` into both of the repositories above (to save time building linuxkit and manifest-tool)

**Comment by deitch** [comment]
Yeah. And you also don't need to clone the whole history. Just one depth would do it fine.
