### ISSUE TITLE
RASPI board is crashing with eden image

### ISSUE THREAD

**Issue by prakeerthi-eden** [lf-edge/eden#604]
**When try to build and Eden from my repo, and test it on the RASPI board, the board is getting rebooted regularly.**

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
**-->  **The system reboot automatically after few minutes.****

# Description
 **cloned latest eden from  github and when I have fallowed the steps mentioned in the below link.
https://wiki.lfedge.org/display/EVE/How+get+Windows+10+running+on+a+Raspberry+Pi
I can see that the board is getting rebooted automatically.
The above can be observed without connecting any USB device (keyboard or mouse).**

**Some times with USB event, device reboots immeditely .**

Briefly describe the problem you are having in a few paragraphs.
**-->Board is getting rebooted  regularly even without performing any activity on the board.**

# Steps to Reproduce
**1. Clone the image from github
2.  build the image
3.  flash the image to the SD card
4.  Insert the SD card in RASPI Sd card slot and power on
5. We can observe reboot after 7-8 minutes** 
# Actual Results

# Expected Results
**Board  should not reboot and from build system we should able to on board the device. (as per the read document  from eden)**

**Comment by Insei** [comment]
Try to clear the sdcard with dd before burning the image. (Step 0 [here](https://github.com/lf-edge/eden#raspberry-pi-4-support))
dd if=/dev/zero bs=1M count=1000 of /dev/{your usb device, example - sdc}
If it does not help, then in order to understand the situation, you need to connect to RPi4 via UART to receive logs. Logs can be left here.

**Comment by prakeerthi-eden** [comment]
By clearing the sd card with the above dd command , it is able to on board the device, and further not rebooting.. But in other cases , board is not able to on board and rebooting regularly.

**Comment by mydatascience** [comment]
hm I will close it for now. We definitely need to do something with clearing the sd card...
