### ISSUE TITLE
Need to think about eden controller  edge-node  eveimage-update a bit more

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#61]
I've been playing with `eden controller  edge-node  eveimage-update` and it is clear to me that this is a pretty tricky one. The biggest problem is how to generate `datastores` and `drives.image.name` portions so that they make most sense. Here's a couple observations I have:

1. first of all, I think we need to make `--image` sub-option  accept an actual URL. That would take care of a use case where I have an EVE image some place publicly available. You will still have to download it locally, calculate a SHA, etc. etc. but at least we will know that you can simply stick the first part of the URL into the `datastore` and the file portion of the URL into the `drives.image.name`.

2. when the file given truly is a file in a local filesystem I starting to think that maybe the best option is to actually rely on somebody else establishing a local tunnel between EVE and a local host (where the file resides). In that sense EVE will get a `datastore` portion that is basically `"fqdn": "http://localhost:8888"` and a `drives.image.name` portion that is a full pathname on the locahost.

The reason I'm leaning towards what I'm describing in #2 is that we probably can't rely on anything but ssh port forwarding when dealing with files on a local filesystem. While it is true that EVE running inside qemu can hit 192.168.1.2 even that is not guaranteed. 

Another option would be to come up with some unique domain name (like eden.local) and then agree that any local file will always be considered to reside on eden.local host (IOW `"fqdn": "http://eden.local:XXXX"` setting in a data store) and it will be a responsibility of however is managing the DHCP/DNS on the outside of EVE to make sure that the name resolves to an appropriate IP address.

Like I said -- #2 here is a tricky one -- need your collective brain power to solve it.

**Comment by giggsoff** [comment]
Hi, @rvs 
#62 includes changes regarding to applying of image from a remote source (http / https):
https://github.com/lf-edge/eden/blob/24b99e507d3a0e92d5e205b313b5f2eea964d2e2/cmd/edenController.go#L496


Regarding the use of the eserver component remotely, the configuration file contains parameters that describe the address:
https://github.com/lf-edge/eden/blob/24b99e507d3a0e92d5e205b313b5f2eea964d2e2/pkg/utils/config.go#L212-L217

**Comment by rvs** [comment]
Fair enough @giggsoff
