### ISSUE TITLE
Eden eve update

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#622]
Let's make 
`eden eve update`
without params - update to latest eve version available 
--file - use eve image specified
--version  - use version specified 
--git - use some eve git repo (if it's possible) . This way we will build eve from the source.  This can take a github/gitlab or some local folder

We may still support this controller command

**Comment by giggsoff** [comment]
What do you mean by `latest eve version`? Is it the latest tagged version or master?
By `git` you mean the link to git with EVE? How we will take care of branch or tag or hash in this case? Can you please provide some examples for your proposed params?
Also, please note, that abstract `file` is not sufficient in general, bacause we forced to know and provide particular version of EVE inside this file.

**Comment by rvs** [comment]
> What do you mean by latest eve version? Is it the latest tagged version or master?

FWIW: our current build infra maintains two floating tags `snapshot` is pointing at the latest build of master and `latest` is pointing at the latest official release
