### ISSUE TITLE
Fix ARM integration tests

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#646]
We have accepted the github actions for ARM integration, but it fails. 
https://github.com/lf-edge/eden/runs/2792351245?check_suite_focus=true
@Insei please have a look. @rvs  did you add the required secrets?

**Comment by Insei** [comment]
@mydatascience, Roman did not add keys because he disagrees with the approach that is used.

**Comment by uncleDecart** [comment]
Closed as stalled issue
