### ISSUE TITLE
Failed to deploy Ubuntu VM on bare metal PC

### ISSUE THREAD

**Issue by lucasvbalves** [lf-edge/eden#648]
# Description

Deploying a VM using the Ubuntu 20.10 image, as in the documentation example, does not work on EVE running on bare metal PC, with the following error: `INSTALLED: [description:"failed to run domain 991666d9-7963-4386-858b-ca4b898ef828.1.1: not based on an OCI image" timestamp:{seconds:1623860477 nanos:500501017}]`

# Steps to Reproduce

Run the commands below to configure EDEN and generate an installable EVE image.

```
git clone https://github.com/lf-edge/eden.git
cd eden
make build
./eden config add default --devmodel general
./eden setup --installer=true
```

The configuration file is generated in `.eden/contexts/default.yml` and the installable image is generated in `eden/dist/default-images/eve/installer.raw`. Use balenaEtcher to flash the installable image onto a USB stick and then use it to install EVE on the remote PC. After installing it, use the commands below to start EDEN and onboard EVE.

```
./eden start
./eden eve onboard
```

After EVE is successfully onboarded, run the command below to deploy the Ubuntu VM.

`./eden pod deploy -p 8027:22 https://cloud-images.ubuntu.com/releases/groovy/release-20210108/ubuntu-20.10-server-cloudimg-amd64.img -v debug --metadata='#cloud-config\npassword: passw0rd\nchpasswd: { expire: False }\nssh_pwauth: True\n'
`

Check deployment status with the command below.

`./eden pod ps`

# Actual Results

`./eden pod ps`
```
NAME: trusting_ishizaka
IMAGE: releases/groovy/release-20210108/ubuntu-20.10-server-cloudimg-amd64.img
UUID: 7a6304c0-b9c6-475a-bfd9-a3cf1b124504
INTERNAL: 10.11.12.2:22
EXTERNAL: 172.21.0.142:8027
MEMORY: 0 B/0 B
STATE(ADAM): IN_CONFIG
LAST_STATE(EVE): INSTALLED: [description:"failed to run domain 7a6304c0-b9c6-475a-bfd9-a3cf1b124504.1.1: not based on an OCI image" timestamp:{seconds:1623860823 nanos:240553145}]
```

# Expected Results

`./eden pod ps`
```
NAME: trusting_ishizaka
IMAGE: releases/groovy/release-20210108/ubuntu-20.10-server-cloudimg-amd64.img
UUID: 7a6304c0-b9c6-475a-bfd9-a3cf1b124504
INTERNAL: 10.11.12.2:22
EXTERNAL: 172.21.0.142:8027
MEMORY: 718 MB/859 MB
STATE(ADAM): IN_CONFIG
LAST_STATE(EVE): RUNNING
```

# Additional Information

My co-worker managed to do the Ubuntu VM deployment running EDEN on her PC in QEMU mode. Maybe there might be a problem with the image for real hardware (x86).

**Comment by mydatascience** [comment]
@lucasvbalves  What was the hardware you were running at? Is nested virtualization enabled? 
Can you deploy a nginx container?

**Comment by lucasvbalves** [comment]
Hi @mydatascience, sorry for the delay to answer you. I was running EVE-OS on bare metal (AMD Ryzen x86 machine). The problem occurred because virtualization was disabled in the machine's BIOS. After I activated this feature in the BIOS I managed to deploy the Ubuntu VM as in the documentation example.

If you allow me, I would like to take this opportunity to ask a few questions.

1. I was able to successfully deploy an Ubuntu Desktop VM from an image created using VirtualBox. However, I had problems deploying a Windows 10 VM also created in VirtualBox. When trying to deploy it on EVE, Windows don't boot and returns a blue screen with the "Inaccessible Boot Device" error. To solve this it was necessary to create the Windows 10 VM using virt-manager and installing the virtIO drivers in the process. So is there any recommended way or tool to create the VMs that will be deployed on EVE in order to get the best performance?
2. Is there any guide to enable GPU on VMs deployed on EVE (GPU passthrough)?

Thanks!

**Comment by rvs** [comment]
Hey @lucasvbalves 

> So is there any recommended way or tool to create the VMs that will be deployed on EVE in order to get the best performance?

There's no official tool (especially not for windows) but things like Packer from Hashicorp are pretty popular

> Is there any guide to enable GPU on VMs deployed on EVE (GPU passthrough)?

Most of the time GPU is just a PCI device and it can be assigned to a VM through a config. We don't currently support GPU slicing. If you have any further questions I recommend you stop by our LF Edge slack (all channels that start with #eve- and ask further questions).
