### ISSUE TITLE
[Feature Request] Add a watch flag to monitor status of deployed pod in eden cli

### ISSUE THREAD

**Issue by shantanoo-desai** [lf-edge/eden#671]
# Description
Once a pod is placed for deployment the status of deployment is always triggered through:

```bash
./eden pod ps
NAME		    IMAGE			        UUID	INTERNAL	    EXTERNAL		    MEMORY	STATE(ADAM)	 LAST_STATE(EVE)
eve_pi_nginx	library/nginx:latest	75de13a4-764f-4b8a-93ac-875eb7390b6e	-:80		192.168.0.103:8027	0 B/0 B	IN_CONFIG	DOWNLOAD_STARTED (39%)
```
This design pattern is rather non-intuitive for UX since a user has to keep triggering to `eden pod ps` everytime
until the status is `RUNNING`

# Steps to Reproduce

1. Deploy an `nginx` pod:
    ```bash
    ./eden pod deploy --name=eve_rpi_nginx docker://nginx \
    -p 8027:80 \
    --mount=src=./data/helloeve,dst=/usr/share/nginx/html
    ```
2.  Keep Checking Status:
     ```bash
     ./eden pod ps
     ```
# Actual Results
```bash
eden pod ps
NAME		    IMAGE			        UUID	INTERNAL	    EXTERNAL		    MEMORY	STATE(ADAM)	 LAST_STATE(EVE)
eve_pi_nginx	library/nginx:latest	75de13a4-764f-4b8a-93ac-875eb7390b6e	-:80		192.168.0.103:8027	0 B/0 B	IN_CONFIG	DOWNLOAD_STARTED (39%)
```

# Expected Results

Something similar to what `kubectl` does with pod status like:

```bash
kubectl get pod -w
```
adding a `-w/--watch` flag in the CLI to keep updating the `LAST_STATE (EVE)` this it reaches `RUNNING` or if user
interrupts using signal SIGINT (by pressing _CTRL+C_)

**Comment by kgiori** [comment]
I think understand the UX improvement goal of this feature request, but let me see if I caught your proposed solution. Do you suggest that a flag such as `-w/--watch` be allowed with `eden pod ps` to enable the result of `eden pod ps -w` to remain visible and be updated continuously until the state reaches `RUNNING`? (or until user exits via ctrl-C)

**Comment by shantanoo-desai** [comment]
@kgiori Yes, depending on how the information is obtained, a better approach is adding a watch flag. This pattern can provide a better understanding of what is currently happening through `STATE_EDEN` and gives the user enough flexibility to interrupt and do other things if ctrl-C is pressed if the user is sure that things are going smooth.
