### ISSUE TITLE
Make set of clean commands

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#68]
Right now cleaning is non-intuitive and there is no "clean everything" 
`eden clean` cleans itself and leaves the config

Suggested:
`make clean `- cleans all  (asks yes /no for config files) 
`eden clean` - cleans all except eden binary
`eden config clean` - cleans all configs (asks yes /no)

**Comment by rvs** [comment]
Agree, but please get rid of make clean -- or to put it another way -- every single make command should be a simply wrapper for a eden command @mydatascience

**Comment by mydatascience** [comment]
then how do I clean eden binary. Counter intuitive for me to have `eden clean `destroy itself.

**Comment by rvs** [comment]
Oh you mean from the perspective of building Eden? Yeah -- that's a totally legit use cases for `make clean`

Agreed!
