### ISSUE TITLE
Comprehensive status

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#69]
Now eden status reflects only whether something is running or not.

Suggested:
If something is running display (except name & status):
1) IP/Port (how to connect) 2) log file location
If something is not running display (except name & status): 
1) Likely cause (if possible) 2) log file location 3) last error from log (something like tail -f)

**Comment by rvs** [comment]
Funny you should mention it @mydatascience -- I was running into a few issues with that myself. In fact, one suggestion I have is to perhaps consider getting rid of PID file tracking -- that's super unreliable anyway -- and make sure to launch processes with some kind of a fake command line flag that you can reliably grep for in the `ps -ale` output (or the equivalent).

**Comment by rvs** [comment]
Btw, @mydatascience -- please take a look at #41 -- I think these issues are identical. Lets pick one and close the other one.
