### ISSUE TITLE
eden config delete need to accept a name as a mandatory argument

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#73]
If there's an agreement on #72 then `eden config delete my-awesome-config` and `eden config set my-awesome-config` also needs to work as expected.

This will effectively make name of the config an mandatory argument

**Comment by mydatascience** [comment]
root@NPC:~/eden# ./eden config delete
INFO[0000] currentContext default                       
INFO[0000] contextName                                  
FATA[0000] Cannot delete default context. Use 'eden clean' instead. 
root@NPC:~/eden# ./eden config add some
INFO[0000] Context file generated: /root/.eden/contexts/some.yml 
root@NPC:~/eden# ./eden config set some
INFO[0000] Current context is: some                     
root@NPC:~/eden# ./eden config delete
INFO[0000] currentContext some                          
INFO[0000] contextName                                  
INFO[0000] Move to default context                      
INFO[0000] currentContextFile /root/.eden/contexts/some.yml 
root@NPC:~/eden# ./eden config list
* default  @sadov

**Comment by mydatascience** [comment]
Done
