### ISSUE TITLE
Move all auxiliary commands to eden utils 

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#88]
Looking at #71 
x509 certificates (current certs subcommand)
Edge Containers (current ociimage subcommand)
EVE live images (current eve-update subcommand)

server command
eserver comand
redis command 

Also remove everything redundant and rename according to #71

**Comment by rvs** [comment]
Ok, so I'd be fine if all "static objects" (from #71 terminology) get moved to under some top level command like utils -- but I think having some but not the others there may be confusing.

Can you post a complete proposal on the wiki someplace @mydatascience ?

**Comment by rvs** [comment]
This appears to be fixed in #171
