### ISSUE TITLE
Add test covering change of controller signing certificate

### ISSUE THREAD

**Issue by milan-zededa** [lf-edge/eden#896]
Recently, we have seen many issues where EVE didn't properly handle a change in the controller signing certificate. It would be therefore beneficial to prepare an eden test in which the signing certificate used by Adam is changed after device is onboarded. This can be combined with poor network connectivity (which can be modeled with eden), etc. (conditions that triggered aforementioned issues).

However, first we must implement a handler in Adam for changing the signing certificate, see: https://github.com/lf-edge/adam/issues/118

CC @eriknordmark @rouming

**Comment by milan-zededa** [comment]
@uncleDecart This is an **enhancement** and a **good first issue** - could you please add those labels, I do not have access.

**Comment by eriknordmark** [comment]
Adding such a test definitely makes sense, particularly if we can do it with network outages and very short lived certifcates (I have a golang tool which can be used to specify certifcate lifetime in seconds as opposed to openssl where the unit is days.)
