### ISSUE TITLE
[0.9.2] collect-info.sh is missing during after failed test on EVE master branch

### ISSUE THREAD

**Issue by uncleDecart** [lf-edge/eden#901]
**Eden version:** 0.9.2

Archive is missing because for some reason collect-info.sh is not found on EVE. referenced works are build on master, which means they use default EVE which is 10.4.0

## Referenced works

[1](https://github.com/lf-edge/eve/actions/runs/6454241589/job/17520292589#step:3:6919), [2](https://github.com/lf-edge/eve/actions/runs/6454241589/job/17520292589#step:3:6845)

**Comment by milan-zededa** [comment]
@uncleDecart the referenced workflows are the same one :)

**Comment by giggsoff** [comment]
> @uncleDecart the referenced workflows are the same one :)

They points onto different lines in workflow. The first one is about not found error in case of SSH attempts, the second one is about not found error in telnet attempt.

**Comment by milan-zededa** [comment]
> > @uncleDecart the referenced workflows are the same one :)
> 
> They point onto different lines in workflow. The first one is about not found error in case of SSH attempts, the second one is about not found error in telnet attempt.

Ah, I see.
Interestingly though, collect info worked just fine for all failed runs in this case: https://github.com/lf-edge/eve/actions/runs/6467321774?pr=3484

**Comment by giggsoff** [comment]
I can see `evebuild/danger:pr-kvm-amd64` [here](https://github.com/lf-edge/eve/actions/runs/6454241589/job/17520292589#step:3:1122) and it looks too broad. Looks like it should point onto image with particular PR number, correct?

**Comment by milan-zededa** [comment]
> I can see `evebuild/danger:pr-kvm-amd64` [here](https://github.com/lf-edge/eve/actions/runs/6454241589/job/17520292589#step:3:1122) and it looks too broad. Looks like it should point onto image with particular PR number, correct?

It should I think. Interestingly, this problematic run shows as job "test_suite", while for PR it should be (and in [this case](https://github.com/lf-edge/eve/actions/runs/6467321774/job/17565501939) is) called "test_suite_pr".

**Comment by giggsoff** [comment]
Well, inside the workflow file I can see that we try to get [pull_request number](https://github.com/lf-edge/eve/actions/runs/6454241589/workflow#L10) when we workflow_dispatch. As I understand it is not possible as workflow_dispatch will point onto the branch head, not PR. But a good question is: where did this workflow come from? I cannot find it in main branch of lf-edge/eve repo.

**Comment by uncleDecart** [comment]
As @milan-zededa mentioned new workflows are working. In latest workflow [file](https://github.com/lf-edge/eve/blob/master/.github/workflows/eden.yml) there's no workflow_dispatch with pr-number. It could be that we were testing if workflow works by running it manually or from fork. 

But I think that this problem is not there anymore since [this](https://github.com/lf-edge/eve/actions/runs/6467321774?pr=3484) worked. I propose we see other workflows and if it's running, we can close this

**Comment by uncleDecart** [comment]
@milan-zededa have you seen any problems with missing collect-info? If not I think we can close this
