### ISSUE TITLE
Storage test suite flakiness

### ISSUE THREAD

**Issue by uncleDecart** [lf-edge/eden#951]
This is a tracker to collect all Storage test suite runs, which failed in GitHub Actions

### How to contribute?

If you see any failure in GitHub actions runs, please add it to this table. 
#### How to find eden version?
Open workflow file of the run and see which eden tag is invoked, like [here](https://github.com/lf-edge/eve/actions/runs/7802284865/workflow#L51) it is 0.9.3. 
#### How to find EVE version?
In setup-job of workflow which failed find eve image parameter which in inputs. For example, [here](https://github.com/lf-edge/eve/actions/runs/7789442745/job/21247727145#step:1:27) it is evebuild/pr:3698. In case if it contains evebuild/pr put PR in it. 

| Link to run | Eden version | EVE version | test | file system |
|-|-|-|-|-|
|[1](https://github.com/lf-edge/eve/actions/runs/7799540369/job/21278601141?pr=3698#step:3:2460) | 0.9.5 |PR|        `volume_test` | zfs |
|[2](https://github.com/lf-edge/eve/actions/runs/7805364625/job/21292407007#step:3:2512)| 0.9.5 | master | `volumes_test` | zfs |
|[3](https://github.com/lf-edge/eden/actions/runs/7844554055/job/21407948409?pr=961#step:3:2524) | master | 11.7.0 | `volumes_test` | zfs |

### How to run suite locally
Clean previous build and add default config with debug level of printing
```bash
make clean && make build-tests
./eden config add default
./eden config set default --key eve.log-level --value debug
```
(optional) set EVE tag to a version you're testing
```
./eden config set default --key eve.tag --value 11.3.0
```
Setup and run a test
```
./eden setup
./dist/bin/eden+ports.sh 2223:2223
./eden start
./eden eve onboard
./eden test ./tests/workflow -s storage.tests.txt -v debug
```

**Comment by eriknordmark** [comment]
A recent run https://github.com/lf-edge/eve/actions/runs/7806282543/job/21310964084?pr=3742 shows the ZFS storage test suite failing to deploy an app instance due to insufficient memory.
Can we easily  increase the memory for the virtual device?

**Comment by uncleDecart** [comment]
> A recent run https://github.com/lf-edge/eve/actions/runs/7806282543/job/21310964084?pr=3742 shows the ZFS storage test suite failing to deploy an app instance due to insufficient memory.
Can we easily increase the memory for the virtual device?

I think yes, maybe @giggsoff knows where exactly. I can take a look later this week

**Comment by giggsoff** [comment]
> > A recent run https://github.com/lf-edge/eve/actions/runs/7806282543/job/21310964084?pr=3742 shows the ZFS storage test suite failing to deploy an app instance due to insufficient memory.
> > Can we easily increase the memory for the virtual device?
> 
> I think yes, maybe @giggsoff knows where exactly. I can take a look later this week

We can add [here](https://github.com/lf-edge/eden/blob/28d635cb3311c91527e04b4e349da5f65ed295c0/.github/actions/setup-environment/action.yml#L57) something like `./eden config set default --key=eve.ram --value=6144`. Or we can increase it by default [here](https://github.com/lf-edge/eden/blob/28d635cb3311c91527e04b4e349da5f65ed295c0/pkg/defaults/defaults.go#L96).

**Comment by uncleDecart** [comment]
>>> A recent run https://github.com/lf-edge/eve/actions/runs/7806282543/job/21310964084?pr=3742 shows the ZFS storage test suite failing to deploy an app instance due to insufficient memory.
        Can we easily increase the memory for the virtual device?

>> I think yes, maybe @giggsoff knows where exactly. I can take a look later this week

> We can add [here](https://github.com/lf-edge/eden/blob/28d635cb3311c91527e04b4e349da5f65ed295c0/.github/actions/setup-environment/action.yml#L57) something like ./eden config set default --key=eve.ram --value=6144. Or we can increase it by default [here](https://github.com/lf-edge/eden/blob/28d635cb3311c91527e04b4e349da5f65ed295c0/pkg/defaults/defaults.go#L96).

In BuildJet we have 16 GBs, but will it work on local forks?.. I'm not so sure. But since we are targeting BuildJet runners, we should be fine

**Comment by giggsoff** [comment]
> > > > A recent run https://github.com/lf-edge/eve/actions/runs/7806282543/job/21310964084?pr=3742 shows the ZFS storage test suite failing to deploy an app instance due to insufficient memory.
> > > > Can we easily increase the memory for the virtual device?
> 
> > > I think yes, maybe @giggsoff knows where exactly. I can take a look later this week
> 
> > We can add [here](https://github.com/lf-edge/eden/blob/28d635cb3311c91527e04b4e349da5f65ed295c0/.github/actions/setup-environment/action.yml#L57) something like ./eden config set default --key=eve.ram --value=6144. Or we can increase it by default [here](https://github.com/lf-edge/eden/blob/28d635cb3311c91527e04b4e349da5f65ed295c0/pkg/defaults/defaults.go#L96).
> 
> In BuildJet we have 16 GBs, but will it work on local forks?.. I'm not so sure. But since we are targeting BuildJet runners, we should be fine

The same memory for GH [hosted](https://docs.github.com/ru/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).

**Comment by uncleDecart** [comment]
Okay so now we fail on other [thing](https://github.com/lf-edge/eden/actions/runs/8077892450/job/22086104046?pr=963#step:3:2533) but that's progress

**Comment by uncleDecart** [comment]
Stabilised. Will open new one if something occurs again
