### ISSUE TITLE
Smoke test suite flakiness

### ISSUE THREAD

**Issue by uncleDecart** [lf-edge/eden#956]
This is a tracker to collect all Smoke test suite runs, which failed in GitHub Actions

### How to contribute?

If you see any failure in GitHub actions runs, please add it to this table. 
#### How to find eden version?
Open workflow file of the run and see which eden tag is invoked, like [here](https://github.com/lf-edge/eve/actions/runs/7802284865/workflow#L51) it is 0.9.3. 
#### How to find EVE version?
In setup-job of workflow which failed find eve image parameter which in inputs. For example, [here](https://github.com/lf-edge/eve/actions/runs/7789442745/job/21247727145#step:1:27) it is evebuild/pr:3698. In case if it contains evebuild/pr put PR in it. 
#### How can I find TPM and File System
It should be in brackets next to run name, for instance [here](https://github.com/lf-edge/eve/actions/runs/7805364625/job/21289418635) name is Smoke tests (ext4, true) which means ext4 file system and TPM is enabled

| Link to run | Eden version | EVE version | test | file system | TPM |
|-|-|-|-|-|-|
|[1](https://github.com/lf-edge/eve/actions/runs/7805364625/job/21289418635#step:3:4039) | 0.9.5 |master|`shutdown_test` | ext4 | enabled |
|[2](https://github.com/lf-edge/eden/actions/runs/7817500697/job/21325541221?pr=954#step:3:1327)| 0.9.5 | PR | `eden_start` | zfs | enabled |
|[3](https://github.com/lf-edge/eden/actions/runs/7844554055/job/21407052446?pr=961#step:3:1559)|0.9.5| 11.7.0 | `eden_onboard`| zfs | enabled | 

### How to run suite locally
Clean previous build and add default config with debug level of printing
```bash
make clean && make build-tests
./eden config add default
./eden config set default --key eve.log-level --value debug
```
(optional) set EVE tag to a version you're testing
```
./eden config set default --key eve.tag --value 11.3.0
```
Setup and run a test
```
./eden setup
./dist/bin/eden+ports.sh 2223:2223
./eden start
./eden eve onboard
./eden test ./tests/workflow -s smoke.tests.txt -v debug
```

**Comment by christoph-zededa** [comment]
see also https://github.com/lf-edge/eve/actions/runs/9192474194/job/25284249864#step:3:2900 ;-)

**Comment by uncleDecart** [comment]
Stabilised. Will open new one if something occurs again
